# Generated by Django 4.2.6 on 2023-11-17 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_alter_post_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Entertainment', 'Entertainment'), ('Educational', 'Educational')], default='Entertainment', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='doc_image',
            field=models.ImageField(default='https://dummyimage.com/900x400/ced4da/6c757d.jpg', upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
