# Generated by Django 4.2.6 on 2023-11-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='doc_image',
            new_name='post_image',
        ),
    ]
